# ----------------
# Add toolbar
# ----------------
/control/execute icons.mac


# ----------------
# Create a Run menu
# ----------------
/gui/addMenu run Run


# ----------------
# Add buttons to the menu
# ----------------

/gui/addButton run "Beam On 100" "/run/beamOn 100"

/gui/addButton run "Run Macro1" "/control/execute run1.mac"

/gui/addButton run "Run Macro2" "/control/execute run2.mac"


