# Macro file for the initialization of example B1
# in interactive session
#
# Set some default verbose
/control/verbose 2
/control/saveHistory
/run/verbose 2
# /process/optical/verbose 0	# Supress output to allow large numbers of photons to be used with optical processes enabled
#
# Change the default number of threads (in multi-threaded mode)
/run/numberOfThreads 4
/PDMPhys/set/reflectivity 0.95
#
# Initialize kernel
/run/initialize

# Visualization setting
/control/execute vis.mac

