# Macro file for the initialization of example B1
# in interactive session
#
# Set some default verbose
/control/verbose 2
#/control/saveHistory
/run/verbose 2
/process/optical/verbose 0	# Supress output to allow large numbers of photons to be used with optical processes enabled
#
/PDMPhys/set/reflectivity 0.98
#
# Initialize kernel
/run/initialize

###############################
### Initialise particle gun ###
###############################
#Pick a gun to use. 

/control/execute gun.mac
